"""empty message

Revision ID: 398c91e8d54f
Revises: d275b9815452
Create Date: 2023-11-16 01:23:05.327324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398c91e8d54f'
down_revision = 'd275b9815452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=480), nullable=False))
        batch_op.add_column(sa.Column('salt', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('salt')
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###
